workflows:
  sample-workflow:
    name: Montreal Skateway
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Montreal Skateway API key
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.MontrealSkateway2025
      vars:
        APP_STORE_APPLE_ID: 6745453530
        BUNDLE_ID: 'com.MontrealSkateway2025'
        XCODE_WORKSPACE: 'MontrealSkateaway.xcworkspace'
        XCODE_SCHEME: 'MontrealSkateaway'
    scripts:
      - name: Install node modules
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profile settings
        script: |
          cd ios
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          echo "Latest build: $LATEST_BUILD_NUMBER"
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          agvtool what-version
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/MontrealSkateaway/Info.plist
          /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" $PLIST
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        copyright: Montreal Skateway 2025
