const lightning = require('../AppAssets/appIcons/lightening.png');
const music = require('../AppAssets/appIcons/music.png');
const wardrobe = require('../AppAssets/appIcons/wardrobe.png');
const skateRental = require('../AppAssets/appIcons/skateRental.png');

const montrealRinks = [
    {
        category: 'OUTDOOR',
        items: [
            {
                name: 'parc la fontaine',
                image: require('../AppAssets/appRinks/ParcLaFontaine.png'),
                rating: '4.6',
                openingHours: '10:00 am - 9:00 pm',
                address: '253 Parkue Park',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '10 CAD',
                skateRentalCost: '5 CAD',
                wardrobe: 'FREE',
                crowdLevel: 'BUSY',
                popularDays: 'SAR, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental, wardrobe]
            },
            {
                name: 'Old Port Skating',
                image: require('../AppAssets/appRinks/OldPortSkating.png'),
                rating: '4.3',
                openingHours: '11:00 am - 8:30 pm',
                address: '333 Rue de la Commune',
                lightning: true,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'NO',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental]
            },
            {
                name: 'parc JARRY',
                image: require('../AppAssets/appRinks/ParkJerry.png'),
                rating: '4.7',
                openingHours: '10:00 am - 9:00 pm',
                address: '5200 RUE DE MENTANA',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '18 CAD',
                skateRentalCost: '8 CAD',
                wardrobe: 'NO',
                crowdLevel: 'NOT BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental]
            },
            {
                name: 'Fougerie',
                image: require('../AppAssets/appRinks/Fougerie.png'),
                rating: '4.8',
                openingHours: '10:00 am - 9:00 pm',
                address: '135 Rue Sherbrooke',
                lightning: true,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'FREE',
                crowdLevel: 'NOT BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental, wardrobe]
            },
        ]
    },
    {
        category: 'INDOOR',
        items: [
            {
                name: 'Atrium Le 1000',
                image: require('../AppAssets/appRinks/Atrium.png'),
                rating: '4.5',
                openingHours: '12:00 am - 4:00 pm',
                address: '3819 RUE DE CALIXA',
                lightning: false,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'FREE',
                crowdLevel: 'NOT BUSY',
                popularDays: 'SUN',
                popularHours: '5:00 pm - 7:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [music, skateRental, wardrobe]
            },
            {
                name: 'Saint-Michel',
                image: require('../AppAssets/appRinks/SaintMichel.png'),
                rating: '4.7',
                openingHours: '11:00 am - 5:00 pm',
                address: '2000 Rue de Chemin',
                lightning: false,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'FREE',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [music, skateRental, wardrobe]
            },
            {
                name: 'Howie-Morenz',
                image: require('../AppAssets/appRinks/HowieMorenz.png'),
                rating: '4.3',
                openingHours: '10:00 pm - 6:00 pm',
                address: '3819 Rue de Lavalée',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '15 CAD',
                skateRentalCost: '5 CAD',
                wardrobe: 'NO',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental]
            },
            {
                name: 'Benny Park',
                image: require('../AppAssets/appRinks/BennyPark.png'),
                rating: '4.6',
                openingHours: '10:00 pm - 9:00 pm',
                address: '253 Parkue Park',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '10 CAD',
                skateRentalCost: '5 CAD',
                wardrobe: 'FREE',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental, wardrobe]
            }
        ]
    },
    {
        category: 'FREE',
        items: [
            {
                name: 'Atrium Le 1000',
                image: require('../AppAssets/appRinks/Atrium.png'),
                rating: '4.5',
                openingHours: '12:00 am - 4:00 pm',
                address: '3819 RUE DE CALIXA',
                lightning: false,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'FREE',
                crowdLevel: 'NOT BUSY',
                popularDays: 'SUN',
                popularHours: '5:00 pm - 7:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [music, skateRental, wardrobe]
            },
            {
                name: 'Old Port Skating',
                image: require('../AppAssets/appRinks/OldPortSkating.png'),
                rating: '4.3',
                openingHours: '11:00 am - 8:30 pm',
                address: '333 Rue de la Commune',
                lightning: true,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'NO',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental]
            },
            {
                name: 'Saint-Michel',
                image: require('../AppAssets/appRinks/SaintMichel.png'),
                rating: '4.7',
                openingHours: '11:00 am - 5:00 pm',
                address: '2000 Rue de Chemin',
                lightning: false,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'FREE',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [music, skateRental, wardrobe]
            },
            {
                name: 'Fougerie',
                image: require('../AppAssets/appRinks/Fougerie.png'),
                rating: '4.8',
                openingHours: '10:00 am - 9:00 pm',
                address: '135 Rue Sherbrooke',
                lightning: true,
                music: true,
                cost: 'FREE',
                sessionsCost: 'FREE',
                skateRentalCost: 'FREE',
                wardrobe: 'FREE',
                crowdLevel: 'NOT BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental, wardrobe]
            }
        ]
    },
    {
        category: 'PAID',
        items: [
            {
                name: 'parc la fontaine',
                image: require('../AppAssets/appRinks/ParcLaFontaine.png'),
                rating: '4.6',
                openingHours: '10:00 am - 9:00 pm',
                address: '253 Parkue Park',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '10 CAD',
                skateRentalCost: '5 CAD',
                wardrobe: 'FREE',
                crowdLevel: 'BUSY',
                popularDays: 'SAR, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental, wardrobe]
            },
            {
                name: 'Howie-Morenz',
                image: require('../AppAssets/appRinks/HowieMorenz.png'),
                rating: '4.3',
                openingHours: '10:00 pm - 6:00 pm',
                address: '3819 Rue de Lavalée',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '15 CAD',
                skateRentalCost: '5 CAD',
                wardrobe: 'NO',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental]
            },
            {
                name: 'parc JARRY',
                image: require('../AppAssets/appRinks/ParkJerry.png'),
                rating: '4.7',
                openingHours: '10:00 am - 9:00 pm',
                address: '5200 RUE DE MENTANA',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '18 CAD',
                skateRentalCost: '8 CAD',
                wardrobe: 'NO',
                crowdLevel: 'NOT BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental]
            },
            {
                name: 'Benny Park',
                image: require('../AppAssets/appRinks/BennyPark.png'),
                rating: '4.6',
                openingHours: '10:00 pm - 9:00 pm',
                address: '253 Parkue Park',
                lightning: true,
                music: true,
                cost: 'PAID',
                sessionsCost: '10 CAD',
                skateRentalCost: '5 CAD',
                wardrobe: 'FREE',
                crowdLevel: 'BUSY',
                popularDays: 'SAT, SUN',
                popularHours: '4:00 pm - 9:00 pm',
                crowdGraph: require('../AppAssets/appRinks/CrowdGraph.png'),
                benefits: [lightning, music, skateRental, wardrobe]
            }
        ]
    }
];

export default montrealRinks;